# Generated by Django 5.1.3 on 2024-11-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe_is_limited_appliances_recipe_is_vegetarian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_desc',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
