# Generated by Django 5.1.3 on 2024-11-25 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_savedrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/'),
        ),
        migrations.CreateModel(
            name='FeaturedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='featured', to='core.recipe')),
            ],
        ),
    ]
